### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by JijiKusahara** [JijiKusahara/chat-space#12]
#IPアドレス
18.179.75.62

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by JijiKusahara** [comment]
確認ありがとうございました！
